# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/graduationproject?useUnicode=true&useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: root
  redis:
    sentinel:
      master: mymaster
      nodes: 47.106.38.101:26379,47.106.38.101:26380
